services:
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn HotelManager.wsgi -b 0.0.0.0:8000 --preload"
    container_name: app
    volumes:
      - .:/app
      - db:/app/db
      - ./db:/app/db
      - ./static:/app/static
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always

volumes:
  db: