# Generated by Django 4.2.1 on 2023-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_booking_updated_at_alter_country_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='packagephoto',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='packagephoto',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='is_active',
            field=models.BooleanField(default=True, editable=False, help_text='This is active status', null=True, verbose_name='Active status'),
        ),
        migrations.AlterField(
            model_name='registerrequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, editable=False, help_text='This is deleted status', null=True, verbose_name='Deleted status'),
        ),
    ]
