# Generated by Django 4.2.1 on 2023-05-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_booking_is_active_alter_booking_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='register_request',
        ),
    ]
