# Generated by Django 4.2.1 on 2023-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_booking_register_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='Date'),
        ),
    ]
