# Generated by Django 4.2.1 on 2023-06-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_booking_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
